### Accessing json file

In [1]:
import pandas as pd
from io import StringIO

df=pd.read_json('iris.json')
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [18]:
df.to_json()

'{"sepalLength":{"0":5.1,"1":4.9,"2":4.7,"3":4.6,"4":5.0,"5":5.4,"6":4.6,"7":5.0,"8":4.4,"9":4.9,"10":5.4,"11":4.8,"12":4.8,"13":4.3,"14":5.8,"15":5.7,"16":5.4,"17":5.1,"18":5.7,"19":5.1,"20":5.4,"21":5.1,"22":4.6,"23":5.1,"24":4.8,"25":5.0,"26":5.0,"27":5.2,"28":5.2,"29":4.7,"30":4.8,"31":5.4,"32":5.2,"33":5.5,"34":4.9,"35":5.0,"36":5.5,"37":4.9,"38":4.4,"39":5.1,"40":5.0,"41":4.5,"42":4.4,"43":5.0,"44":5.1,"45":4.8,"46":5.1,"47":4.6,"48":5.3,"49":5.0,"50":7.0,"51":6.4,"52":6.9,"53":5.5,"54":6.5,"55":5.7,"56":6.3,"57":4.9,"58":6.6,"59":5.2,"60":5.0,"61":5.9,"62":6.0,"63":6.1,"64":5.6,"65":6.7,"66":5.6,"67":5.8,"68":6.2,"69":5.6,"70":5.9,"71":6.1,"72":6.3,"73":6.1,"74":6.4,"75":6.6,"76":6.8,"77":6.7,"78":6.0,"79":5.7,"80":5.5,"81":5.5,"82":5.8,"83":6.0,"84":5.4,"85":6.0,"86":6.7,"87":6.3,"88":5.6,"89":5.5,"90":5.5,"91":6.1,"92":5.8,"93":5.0,"94":5.6,"95":5.7,"96":5.7,"97":6.2,"98":5.1,"99":5.7,"100":6.3,"101":5.8,"102":7.1,"103":6.3,"104":6.5,"105":7.6,"106":4.9,"107":7.3,"108":6.7,"109":7.2,"110":6.5,"111":6.4,"112":6.8,"113":5.7,"114":5.8,"115":6.4,"116":6.5,"117":7.7,"118":7.7,"119":6.0,"120":6.9,"121":5.6,"122":7.7,"123":6.3,"124":6.7,"125":7.2,"126":6.2,"127":6.1,"128":6.4,"129":7.2,"130":7.4,"131":7.9,"132":6.4,"133":6.3,"134":6.1,"135":7.7,"136":6.3,"137":6.4,"138":6.0,"139":6.9,"140":6.7,"141":6.9,"142":5.8,"143":6.8,"144":6.7,"145":6.7,"146":6.3,"147":6.5,"148":6.2,"149":5.9},"sepalWidth":{"0":3.5,"1":3.0,"2":3.2,"3":3.1,"4":3.6,"5":3.9,"6":3.4,"7":3.4,"8":2.9,"9":3.1,"10":3.7,"11":3.4,"12":3.0,"13":3.0,"14":4.0,"15":4.4,"16":3.9,"17":3.5,"18":3.8,"19":3.8,"20":3.4,"21":3.7,"22":3.6,"23":3.3,"24":3.4,"25":3.0,"26":3.4,"27":3.5,"28":3.4,"29":3.2,"30":3.1,"31":3.4,"32":4.1,"33":4.2,"34":3.1,"35":3.2,"36":3.5,"37":3.6,"38":3.0,"39":3.4,"40":3.5,"41":2.3,"42":3.2,"43":3.5,"44":3.8,"45":3.0,"46":3.8,"47":3.2,"48":3.7,"49":3.3,"50":3.2,"51":3.2,"52":3.1,"53":2.3,"54":2.8,"55":2.8,"56":3.3,"57":2.4,"58":2.9,"59":2.7,"60":2.0,"61":3.0,"62":2.2,"63":2.9,"64":2.9,"65":3.1,"66":3.0,"67":2.7,"68":2.2,"69":2.5,"70":3.2,"71":2.8,"72":2.5,"73":2.8,"74":2.9,"75":3.0,"76":2.8,"77":3.0,"78":2.9,"79":2.6,"80":2.4,"81":2.4,"82":2.7,"83":2.7,"84":3.0,"85":3.4,"86":3.1,"87":2.3,"88":3.0,"89":2.5,"90":2.6,"91":3.0,"92":2.6,"93":2.3,"94":2.7,"95":3.0,"96":2.9,"97":2.9,"98":2.5,"99":2.8,"100":3.3,"101":2.7,"102":3.0,"103":2.9,"104":3.0,"105":3.0,"106":2.5,"107":2.9,"108":2.5,"109":3.6,"110":3.2,"111":2.7,"112":3.0,"113":2.5,"114":2.8,"115":3.2,"116":3.0,"117":3.8,"118":2.6,"119":2.2,"120":3.2,"121":2.8,"122":2.8,"123":2.7,"124":3.3,"125":3.2,"126":2.8,"127":3.0,"128":2.8,"129":3.0,"130":2.8,"131":3.8,"132":2.8,"133":2.8,"134":2.6,"135":3.0,"136":3.4,"137":3.1,"138":3.0,"139":3.1,"140":3.1,"141":3.1,"142":2.7,"143":3.2,"144":3.3,"145":3.0,"146":2.5,"147":3.0,"148":3.4,"149":3.0},"petalLength":{"0":1.4,"1":1.4,"2":1.3,"3":1.5,"4":1.4,"5":1.7,"6":1.4,"7":1.5,"8":1.4,"9":1.5,"10":1.5,"11":1.6,"12":1.4,"13":1.1,"14":1.2,"15":1.5,"16":1.3,"17":1.4,"18":1.7,"19":1.5,"20":1.7,"21":1.5,"22":1.0,"23":1.7,"24":1.9,"25":1.6,"26":1.6,"27":1.5,"28":1.4,"29":1.6,"30":1.6,"31":1.5,"32":1.5,"33":1.4,"34":1.5,"35":1.2,"36":1.3,"37":1.4,"38":1.3,"39":1.5,"40":1.3,"41":1.3,"42":1.3,"43":1.6,"44":1.9,"45":1.4,"46":1.6,"47":1.4,"48":1.5,"49":1.4,"50":4.7,"51":4.5,"52":4.9,"53":4.0,"54":4.6,"55":4.5,"56":4.7,"57":3.3,"58":4.6,"59":3.9,"60":3.5,"61":4.2,"62":4.0,"63":4.7,"64":3.6,"65":4.4,"66":4.5,"67":4.1,"68":4.5,"69":3.9,"70":4.8,"71":4.0,"72":4.9,"73":4.7,"74":4.3,"75":4.4,"76":4.8,"77":5.0,"78":4.5,"79":3.5,"80":3.8,"81":3.7,"82":3.9,"83":5.1,"84":4.5,"85":4.5,"86":4.7,"87":4.4,"88":4.1,"89":4.0,"90":4.4,"91":4.6,"92":4.0,"93":3.3,"94":4.2,"95":4.2,"96":4.2,"97":4.3,"98":3.0,"99":4.1,"100":6.0,"101":5.1,"102":5.9,"103":5.6,"104":5.8,"105":6.6,"106":4.5,"107":6.3,"108":5.8,"109":6.1,"110":5.1,"111":5.3,"112":5.5,"113":5.0,"114":5.1,"115":5.3,"116":5.5,"117":6.7,"118":6.9,"119":5.0,"120":5.7,"121":4.9,"122":6.7,"123":4.9,"124":5.7,"125":6.0,"126":4.8,"127":4.9,"128":5.6,"129":5.8,"130":6.1,"131":6.4,"132":5.6,"133":5.1,"134":5.6,"135":6.1,"136":5.6,"137":5.5,"138":4.8,"139":5.4,"140":5.6,"141":5.1,"142":5.1,"143":5.9,"144":5.7,"145":5.2,"146":5.0,"147":5.2,"148":5.4,"149":5.1},"petalWidth":{"0":0.2,"1":0.2,"2":0.2,"3":0.2,"4":0.2,"5":0.4,"6":0.3,"7":0.2,"8":0.2,"9":0.1,"10":0.2,"11":0.2,"12":0.1,"13":0.1,"14":0.2,"15":0.4,"16":0.4,"17":0.3,"18":0.3,"19":0.3,"20":0.2,"21":0.4,"22":0.2,"23":0.5,"24":0.2,"25":0.2,"26":0.4,"27":0.2,"28":0.2,"29":0.2,"30":0.2,"31":0.4,"32":0.1,"33":0.2,"34":0.2,"35":0.2,"36":0.2,"37":0.1,"38":0.2,"39":0.2,"40":0.3,"41":0.3,"42":0.2,"43":0.6,"44":0.4,"45":0.3,"46":0.2,"47":0.2,"48":0.2,"49":0.2,"50":1.4,"51":1.5,"52":1.5,"53":1.3,"54":1.5,"55":1.3,"56":1.6,"57":1.0,"58":1.3,"59":1.4,"60":1.0,"61":1.5,"62":1.0,"63":1.4,"64":1.3,"65":1.4,"66":1.5,"67":1.0,"68":1.5,"69":1.1,"70":1.8,"71":1.3,"72":1.5,"73":1.2,"74":1.3,"75":1.4,"76":1.4,"77":1.7,"78":1.5,"79":1.0,"80":1.1,"81":1.0,"82":1.2,"83":1.6,"84":1.5,"85":1.6,"86":1.5,"87":1.3,"88":1.3,"89":1.3,"90":1.2,"91":1.4,"92":1.2,"93":1.0,"94":1.3,"95":1.2,"96":1.3,"97":1.3,"98":1.1,"99":1.3,"100":2.5,"101":1.9,"102":2.1,"103":1.8,"104":2.2,"105":2.1,"106":1.7,"107":1.8,"108":1.8,"109":2.5,"110":2.0,"111":1.9,"112":2.1,"113":2.0,"114":2.4,"115":2.3,"116":1.8,"117":2.2,"118":2.3,"119":1.5,"120":2.3,"121":2.0,"122":2.0,"123":1.8,"124":2.1,"125":1.8,"126":1.8,"127":1.8,"128":2.1,"129":1.6,"130":1.9,"131":2.0,"132":2.2,"133":1.5,"134":1.4,"135":2.3,"136":2.4,"137":1.8,"138":1.8,"139":2.1,"140":2.4,"141":2.3,"142":1.9,"143":2.3,"144":2.5,"145":2.3,"146":1.9,"147":2.0,"148":2.3,"149":1.8},"species":{"0":"setosa","1":"setosa","2":"setosa","3":"setosa","4":"setosa","5":"setosa","6":"setosa","7":"setosa","8":"setosa","9":"setosa","10":"setosa","11":"setosa","12":"setosa","13":"setosa","14":"setosa","15":"setosa","16":"setosa","17":"setosa","18":"setosa","19":"setosa","20":"setosa","21":"setosa","22":"setosa","23":"setosa","24":"setosa","25":"setosa","26":"setosa","27":"setosa","28":"setosa","29":"setosa","30":"setosa","31":"setosa","32":"setosa","33":"setosa","34":"setosa","35":"setosa","36":"setosa","37":"setosa","38":"setosa","39":"setosa","40":"setosa","41":"setosa","42":"setosa","43":"setosa","44":"setosa","45":"setosa","46":"setosa","47":"setosa","48":"setosa","49":"setosa","50":"versicolor","51":"versicolor","52":"versicolor","53":"versicolor","54":"versicolor","55":"versicolor","56":"versicolor","57":"versicolor","58":"versicolor","59":"versicolor","60":"versicolor","61":"versicolor","62":"versicolor","63":"versicolor","64":"versicolor","65":"versicolor","66":"versicolor","67":"versicolor","68":"versicolor","69":"versicolor","70":"versicolor","71":"versicolor","72":"versicolor","73":"versicolor","74":"versicolor","75":"versicolor","76":"versicolor","77":"versicolor","78":"versicolor","79":"versicolor","80":"versicolor","81":"versicolor","82":"versicolor","83":"versicolor","84":"versicolor","85":"versicolor","86":"versicolor","87":"versicolor","88":"versicolor","89":"versicolor","90":"versicolor","91":"versicolor","92":"versicolor","93":"versicolor","94":"versicolor","95":"versicolor","96":"versicolor","97":"versicolor","98":"versicolor","99":"versicolor","100":"virginica","101":"virginica","102":"virginica","103":"virginica","104":"virginica","105":"virginica","106":"virginica","107":"virginica","108":"virginica","109":"virginica","110":"virginica","111":"virginica","112":"virginica","113":"virginica","114":"virginica","115":"virginica","116":"virginica","117":"virginica","118":"virginica","119":"virginica","120":"virginica","121":"virginica","122":"virginica","123":"virginica","124":"virginica","125":"virginica","126":"virginica","127":"virginica","128":"virginica","129":"virginica","130":"virginica","131":"virginica","132":"virginica","133":"virginica","134":"virginica","135":"virginica","136":"virginica","137":"virginica","138":"virginica","139":"virginica","140":"virginica","141":"virginica","142":"virginica","143":"virginica","144":"virginica","145":"virginica","146":"virginica","147":"virginica","148":"virginica","149":"virginica"}}'

In [22]:
url ="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)
df

[                               Bank Name               City          State  \
 0     The First National Bank of Lindsay            Lindsay       Oklahoma
 1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania
 2                          Citizens Bank           Sac City           Iowa
 3               Heartland Tri-State Bank            Elkhart         Kansas
 4                    First Republic Bank      San Francisco     California
 5                         Signature Bank           New York       New York
 6                    Silicon Valley Bank        Santa Clara     California
 7                      Almena State Bank             Almena         Kansas
 8             First City Bank of Florida  Fort Walton Beach        Florida
 9                   The First State Bank      Barboursville  West Virginia

     Cert                 Aquiring Institution      Closing Date  \
 0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024
 1  27332    Fulton Bank, National Association    April 26, 2024
 2   8758            Iowa Trust & Savings Bank  November 3, 2023
 3  25851               Dream First Bank, N.A.     July 28, 2023
 4  59017            JPMorgan Chase Bank, N.A.       May 1, 2023
 5  57053                  Flagstar Bank, N.A.    March 12, 2023
 6  24735  First Citizens Bank & Trust Company    March 10, 2023
 7  15426                          Equity Bank  October 23, 2020
 8  16748            United Fidelity Bank, fsb  October 16, 2020
 9  14361                       MVB Bank, Inc.     April 3, 2020

    Fund  Sort ascending
 0                 10547
 1                 10546
 2                 10545
 3                 10544
 4                 10543
 5                 10540
 6                 10539
 7                 10538
 8                 10537
 9                 10536  ]

In [23]:
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [49]:
df = sns.load_dataset('titanic')
print(df.head())
df.isnull().sum()

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [31]:
df['updated_age']=df['age'].fillna(df['age'].mean())

In [28]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [42]:
df[['age','updated_age','deck']]

      age  updated_age deck
0    22.0    22.000000  NaN
1    38.0    38.000000    C
2    26.0    26.000000  NaN
3    35.0    35.000000    C
4    35.0    35.000000  NaN
..    ...          ...  ...
886  27.0    27.000000  NaN
887  19.0    19.000000    B
888   NaN    29.699118  NaN
889  26.0    26.000000    C
890  32.0    32.000000  NaN

[891 rows x 3 columns]

In [84]:
mode_value=df[df['deck'].notna()]['deck'].mode()[0]
mode_value

'C'

In [85]:
df['deck_updated']=df['deck'].fillna(mode_value)
df['deck_updated'].isnull().sum()

np.int64(0)

In [65]:
df[df['deck_updated'].isnull()][['deck','deck_updated']].isnull().sum()

deck            687
deck_updated    687
dtype: int64

In [86]:
df[['deck','deck_updated']]

    deck deck_updated
0    NaN            C
1      C            C
2    NaN            C
3      C            C
4    NaN            C
..   ...          ...
886  NaN            C
887    B            B
888  NaN            C
889    C            C
890  NaN            C

[891 rows x 2 columns]

In [45]:
import numpy as np
np.random.seed(1)
df=pd.DataFrame(np.random.randint(1,100,size=(3,3)),columns=['a','b','c'])
df

    a   b   c
0  38  13  73
1  10  76   6
2  80  65  17

In [5]:
def sum1(l):
    element_sum=0
    for i in l:
        element_sum+=i
    return element_sum

l1=[1,2,3,4,5]
print(f"sum ={sum1(l1)}")   
try:
    l2=['a','b','c']
    s=sum1(l1)
except TypeError:
    print("data type should be int")

sum =15

In [6]:
def value_of_key(d):
    key=str(input('enter the key'))
    return d[f'{key}']

try:
    d1={
    'name':'barun',
    'age':23
}
    result=value_of_key(d1)
    
except KeyError:
    print('Enter the right key')
finally:
    print(result)

barun